### ISSUE TITLE
KeyError when unable to parse city

### ISSUE THREAD

**Issue by rennerocha** [kalessin/japanese-address#3]
If the city are not parsed, it is raising a KeyError:

```Traceback (most recent call last):
  File "/home/renne/.pyenv/versions/3.11.6/envs/crawler/lib/python3.11/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/renne/.pyenv/versions/3.11.6/envs/crawler/lib/python3.11/site-packages/scrapy/utils/defer.py", line 340, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "/home/renne/projects/rennerocha/crawler/pipelines.py", line 18, in process_item
    parsed_address = parse(address)
  File "/home/renne/.pyenv/versions/3.11.6/envs/crawler/lib/python3.11/site-packages/japanese_address/__init__.py", line 95, in parse
    parsed['city_eng'] = CITIES_DATA[parsed['city']]
KeyError: '冨安2-138-4 鳥取市'
```

**Comment by kalessin** [comment]
Is this issue fixed with your PR?

**Comment by rennerocha** [comment]
Not entirely. Probably it will still fail if the city is not in `CITIES_DATA`. But I didn't want to fix it before merging #4 , as this PR changes a lot of the project structure. If you are ok with the PR, please merge, so I can create a second PR fixing this issue too.
